import { ShieldCheck } from "lucide-react";
import { GitHubIcon, Logo, REPO_URL } from "./Brand";

const COLUMNS: { title: string; links: { label: string; href: string }[] }[] = [
  {
    title: "Product",
    links: [
      { label: "How it works", href: "#how-it-works" },
      { label: "Run an audit", href: "#audit" },
      { label: "Source code", href: REPO_URL },
    ],
  },
  {
    title: "Built with",
    links: [
      { label: "Cloudinary", href: "https://cloudinary.com" },
      { label: "Next.js", href: "https://nextjs.org" },
      { label: "Google Gemini", href: "https://ai.google.dev" },
    ],
  },
  {
    title: "Hackathon",
    links: [
      { label: "Pixels to Products 2026", href: "https://cld.media/hackathons" },
      { label: "HackIndia", href: "https://hackindia.org" },
    ],
  },
];

export function SiteFooter() {
  return (
    <footer className="border-line bg-surface/40 mt-28 border-t">
      <div className="mx-auto grid w-full max-w-5xl gap-10 px-4 py-14 md:grid-cols-[1.4fr_repeat(3,1fr)]">
        <div>
          <div className="flex items-center gap-2.5">
            <Logo />
            <span className="text-ink font-serif text-2xl leading-none">Echo</span>
          </div>
          <p className="text-ink-2 mt-4 max-w-xs text-sm leading-relaxed">
            See whether AI recommends your brand, in words and in pictures, and fix
            what it gets wrong.
          </p>
          <p className="text-ink-muted mt-5 flex items-start gap-2 text-xs leading-relaxed">
            <ShieldCheck size={14} className="mt-px shrink-0" aria-hidden />
            Probes never name your brand, and every figure is computed in code
            from the answers, not generated by a model.
          </p>
        </div>

        {COLUMNS.map((column) => (
          <div key={column.title}>
            <h3 className="text-ink-muted font-mono text-xs tracking-widest uppercase">{column.title}</h3>
            <ul className="mt-4 space-y-2.5">
              {column.links.map((link) => {
                const external = link.href.startsWith("http");
                return (
                  <li key={link.label}>
                    <a
                      href={link.href}
                      {...(external ? { target: "_blank", rel: "noreferrer" } : {})}
                      className="text-ink-2 hover:text-ink text-sm transition-colors"
                    >
                      {link.label}
                    </a>
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </div>

      <div className="border-line border-t">
        <div className="text-ink-muted mx-auto flex w-full max-w-5xl flex-col gap-3 px-4 py-6 text-xs sm:flex-row sm:items-center sm:justify-between">
          <p>© 2026 TamilLoft · Built for the Cloudinary AI Hackathon, Track 1: AI Media Pipelines</p>
          <a href={REPO_URL} target="_blank" rel="noreferrer" className="hover:text-ink-2 flex items-center gap-1.5">
            <GitHubIcon size={14} />
            HackIndiaXYZ/…tamilloft
          </a>
        </div>
      </div>
    </footer>
  );
}
